apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: server
  strategy:
    rollingUpdate:
      maxSurge: 33%
      maxUnavailable: 33%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: ghcr.io/paulopacitti/skynet-server:main
        imagePullPolicy: IfNotPresent
        name: server
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "350m"
        ports:
        - containerPort: 50001
          protocol: TCP