apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 50001
    protocol: TCP
    targetPort: 50001
  selector:
    app: server
  sessionAffinity: None
  type: LoadBalancer